sgx_vma: return unsigned int from sgx_vma_fault
For kernel v5.1.x, compiling the out-of-tree 'isgx' driver led to the
following error:
sgx_vma.c:241:11: error: initialization of 'vm_fault_t (*)(struct
vm_fault *)' {aka 'unsigned int (*)(struct vm_fault *)'} from
incompatible pointer type 'int (*)(struct vm_fault *)'
[-Werror=incompatible-pointer-types]

Hence, added return type of unsigned int to sgx_vma_fault for kernel
v5.1.

Signed-off-by: Iyer, Naveen <naveen.iyer@intel.com>